# Generated by Django 5.2.3 on 2026-01-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_birthday_person_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
