# Generated by Django 5.2.3 on 2026-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_person_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_big_release',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
