# Generated by Django 5.2.3 on 2026-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_is_big_release_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
