# Generated by Django 5.2.3 on 2026-01-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_person_instagram_id_person_twitter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='twitter_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='youtube_id',
        ),
    ]
