# Generated by Django 5.2.3 on 2026-01-22 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_reviewcomment_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='review_text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
