# Generated by Django 5.2.3 on 2026-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_moviereview_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='contains_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
