# Generated by Django 5.2.3 on 2026-01-23 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_moviereview_contains_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
