# Generated by Django 5.2.3 on 2026-01-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_moviehypevote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
