# Generated by Django 5.2.3 on 2026-01-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_delete_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='cons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='pros',
            field=models.TextField(blank=True, default=''),
        ),
    ]
