# Generated by Django 5.2.3 on 2026-01-26 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_moviereview_cons_moviereview_pros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='pros',
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rewrite', 'Rewrite'), ('shorten', 'Shorten'), ('tone', 'Tone Change'), ('pros_cons', 'Pros & Cons')], max_length=20)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
