# Generated by Django 5.2.3 on 2026-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_moviereview_cons_remove_moviereview_pros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='action',
            field=models.CharField(choices=[('rewrite', 'Rewrite'), ('shorten', 'Shorten'), ('funny', 'Funny'), ('roast', 'Roast'), ('professional', 'Professional'), ('hype', 'Hype'), ('savage_1star', 'Savage 1-Star'), ('pros_cons', 'Pros & Cons')], max_length=20),
        ),
    ]
