# Generated by Django 5.2.3 on 2026-01-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_airequestlog_action'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_title_652549_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_release_b7ac7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_is_rele_fa59b0_idx',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_big_release',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
